Homework 2
================
Kehan Su ks4186
2024-10-02

``` r
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

## Problem 1

## import data

``` r
subway_df = 
  read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) |> 
  janitor::clean_names() |> 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) |> 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
print(subway_df)
```

    ## # A tibble: 1,868 × 20
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 13 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>, entry <lgl>,
    ## #   exit_only <chr>, vending <chr>, entrance_type <chr>, ada <lgl>

## Problem 2

## date cleaning for Mr TW

``` r
MrTW_df = read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = 1) |>
  janitor::clean_names() |>
  select (-x15, -x16) |>
  filter(!is.na(dumpster)) |>
  mutate(sports_balls = as.integer(round(sports_balls, 0))) |>
  mutate(trash_wheel = "Mr. Trash Wheel") |>
  relocate (trash_wheel) |>
  mutate(year=as.character(year))
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

## data cleaning for Prof TW and Gwynnda TW

``` r
ProfTW_df = read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = 2) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster), !is.na(month)) |>
  mutate(trash_wheel = "Professor Trash Wheel") |>
  relocate (trash_wheel) |>
  mutate(year=as.character(year))

Gwyn_df = read_excel("./data/202409 Trash Wheel Collection Data.xlsx", sheet = 4) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster), !is.na(month)) |>
  mutate(trash_wheel = "Gwynnda Trash Wheel") |>
  relocate (trash_wheel) |>
  mutate(year=as.character(year))
```

## merge together

``` r
final_df = 
  bind_rows(MrTW_df,ProfTW_df,Gwyn_df) |>
  janitor::clean_names()
```

The final dataset contains 1032 observations of 15 variables, key
variables include dumpster, month, year, date, weight, volume, types of
trash (plastic bottles, cigarette butts, etc.)

``` r
sum(pull(ProfTW_df, weight_tons), na.rm = TRUE)
```

    ## [1] 246.74

The total weight of trash collected by Professor Trash Wheel is 246.74
tons.

``` r
final_df |>
  filter(trash_wheel == "Gwynnda Trash Wheel", month == "June", year == "2022") |>
  summarise(Gwy_cigbutts_total = sum(cigarette_butts, na.rm = TRUE))
```

    ## # A tibble: 1 × 1
    ##   Gwy_cigbutts_total
    ##                <dbl>
    ## 1              18120

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120.

## Problem 3

## import dataset

``` r
bakers_df = 
  read_csv("./gbb_datasets/bakers.csv", na = c("NA","",".")) |>
  janitor::clean_names() |>
  mutate(series = as.character(series)) |>
  mutate(name = word(baker_name,1))
```

    ## Rows: 120 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker Name, Baker Occupation, Hometown
    ## dbl (2): Series, Baker Age
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

I import the data through relative path, and clean the missing data.
Then use janitor::clean_names() to clean up variable names. Then, I
convert series variable into character, and extract first name of the
backers to match with the names in other datasets.

``` r
bakes_df = 
  read_csv("./gbb_datasets/bakes.csv", na = c("NA","",".")) |>
  janitor::clean_names() |>
  mutate(baker = str_replace_all(baker, '"',"")) |>
  relocate(baker) |>
  rename(name = baker) |>
  mutate(series = as.character(series)) |>
  mutate(episode = as.character(episode)) |>
  arrange(name)
```

    ## Rows: 548 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Baker, Signature Bake, Show Stopper
    ## dbl (2): Series, Episode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

I import the data through relative path, and clean the missing data.
Then use janitor::clean_names() to clean up variable names. Then, I
convert series and episode variables into character. I rename “bakers”
to “name” to match with the names in other datasets. I notice that there
are “” in baker’s name, and i delete them.

``` r
results_df =
  read_csv("./gbb_datasets/results.csv", na = c("NA","","."), skip = 2) |>
  janitor::clean_names() |>
  mutate(series = as.character(series)) |>
  mutate(episode = as.character(episode)) |>
  mutate(baker = str_replace_all(baker, "Joanne","Jo")) |>
  rename(name = baker)
```

    ## Rows: 1136 Columns: 5
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (2): baker, result
    ## dbl (3): series, episode, technical
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

I import the data through relative path, and clean the missing data.
Then use janitor::clean_names() to clean up variable names. Then, I
convert series and episode variables into character. Through the process
of correctness, I found that “Jo” in backers_df and bakes_df is “Joanne”
in results_df. So I replace all the “Joanne” in results_df with “Jo” to
macth names in all datasets.

## completeness & correctness

``` r
bakers_not_in_bakes_df =
  anti_join(bakers_df, bakes_df, by = c("name", "series"))
backers_not_in_results_df =
  anti_join(bakers_df, results_df, by = c("name", "series"))
bakes_not_in_results_df = 
  anti_join(bakes_df, results_df, by = c("name", "series"))
```

``` r
results_not_in_bakers_df = 
  anti_join(results_df, bakers_df, by = c("name", "series"))
```

This helps me find that “Jo” in backers_df and bakes_df is “Joanne” in
results_df.

## merge data

``` r
merged_df =
  bakers_df |>
  left_join(bakes_df, by = c("name", "series")) |>
  left_join(results_df, by = c("name", "series", "episode"))
```

There are 573 observation in the merged_df, containing 11 variables
including key variables like names, occupation, series, episode, age,
signature_bake, result, etc.

## table

``` r
winner_bakers_df = 
  merged_df |>
  filter(series >= 5) |>
  filter(result %in% c("WINNER", "STAR BAKER")) |>
  select (name, series, episode, result)
```

Candice and Nadiya are predictable overall winners as they thave won
star bakers several times before the final winner. Nancy is surprising
as she only won one star bakers before. Another impressive person is
Rechard as he wone five star bakers but did not won the winner.

## import viewer

``` r
viewer_df=
  read_csv("./gbb_datasets/viewers.csv", na = c("NA","",".")) |>
  janitor::clean_names() |>
  pivot_longer(
    series_1:series_10,
    names_to = "series",
    values_to = "viewship"
  ) |>
  arrange(series) |>
  head(10)
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
viewers_df=
  read_csv("./gbb_datasets/viewers.csv", na = c("NA","",".")) |>
  janitor::clean_names()
```

    ## Rows: 10 Columns: 11
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (11): Episode, Series 1, Series 2, Series 3, Series 4, Series 5, Series ...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mean(pull(viewers_df,"series_1"), na.rm = TRUE)
```

    ## [1] 2.77

``` r
mean(pull(viewers_df,"series_5"),na.rm = TRUE)
```

    ## [1] 10.0393

The average viewership in season 1 is 2.77. The average viewership in
season 1 is 10.0393.
